# Generated by Django 3.0.3 on 2020-02-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='answer',
        ),
    ]
