# Generated by Django 3.0.3 on 2020-06-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_mission_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mission',
        ),
    ]
